-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module FreeFoilTypecheck.HindleyMilner.Parser.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified FreeFoilTypecheck.HindleyMilner.Parser.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: FreeFoilTypecheck.HindleyMilner.Parser.Abs.Ident -> Result
transIdent x = case x of
  FreeFoilTypecheck.HindleyMilner.Parser.Abs.Ident string -> failure x

transUVarIdent :: FreeFoilTypecheck.HindleyMilner.Parser.Abs.UVarIdent -> Result
transUVarIdent x = case x of
  FreeFoilTypecheck.HindleyMilner.Parser.Abs.UVarIdent string -> failure x

transPattern :: FreeFoilTypecheck.HindleyMilner.Parser.Abs.Pattern -> Result
transPattern x = case x of
  FreeFoilTypecheck.HindleyMilner.Parser.Abs.PatternVar ident -> failure x

transExp :: FreeFoilTypecheck.HindleyMilner.Parser.Abs.Exp -> Result
transExp x = case x of
  FreeFoilTypecheck.HindleyMilner.Parser.Abs.EVar ident -> failure x
  FreeFoilTypecheck.HindleyMilner.Parser.Abs.ETrue -> failure x
  FreeFoilTypecheck.HindleyMilner.Parser.Abs.EFalse -> failure x
  FreeFoilTypecheck.HindleyMilner.Parser.Abs.ENat integer -> failure x
  FreeFoilTypecheck.HindleyMilner.Parser.Abs.EAdd exp1 exp2 -> failure x
  FreeFoilTypecheck.HindleyMilner.Parser.Abs.ESub exp1 exp2 -> failure x
  FreeFoilTypecheck.HindleyMilner.Parser.Abs.EIf exp1 exp2 exp3 -> failure x
  FreeFoilTypecheck.HindleyMilner.Parser.Abs.EIsZero exp -> failure x
  FreeFoilTypecheck.HindleyMilner.Parser.Abs.ETyped exp type_ -> failure x
  FreeFoilTypecheck.HindleyMilner.Parser.Abs.ELet pattern_ exp scopedexp -> failure x
  FreeFoilTypecheck.HindleyMilner.Parser.Abs.EAbs pattern_ scopedexp -> failure x
  FreeFoilTypecheck.HindleyMilner.Parser.Abs.EApp exp1 exp2 -> failure x
  FreeFoilTypecheck.HindleyMilner.Parser.Abs.EFor pattern_ exp1 exp2 scopedexp -> failure x

transScopedExp :: FreeFoilTypecheck.HindleyMilner.Parser.Abs.ScopedExp -> Result
transScopedExp x = case x of
  FreeFoilTypecheck.HindleyMilner.Parser.Abs.ScopedExp exp -> failure x

transTypePattern :: FreeFoilTypecheck.HindleyMilner.Parser.Abs.TypePattern -> Result
transTypePattern x = case x of
  FreeFoilTypecheck.HindleyMilner.Parser.Abs.TPatternVar ident -> failure x

transType :: FreeFoilTypecheck.HindleyMilner.Parser.Abs.Type -> Result
transType x = case x of
  FreeFoilTypecheck.HindleyMilner.Parser.Abs.TUVar uvarident -> failure x
  FreeFoilTypecheck.HindleyMilner.Parser.Abs.TNat -> failure x
  FreeFoilTypecheck.HindleyMilner.Parser.Abs.TBool -> failure x
  FreeFoilTypecheck.HindleyMilner.Parser.Abs.TArrow type_1 type_2 -> failure x
  FreeFoilTypecheck.HindleyMilner.Parser.Abs.TVar ident -> failure x
  FreeFoilTypecheck.HindleyMilner.Parser.Abs.TForAll typepattern scopedtype -> failure x

transScopedType :: FreeFoilTypecheck.HindleyMilner.Parser.Abs.ScopedType -> Result
transScopedType x = case x of
  FreeFoilTypecheck.HindleyMilner.Parser.Abs.ScopedType type_ -> failure x
