name: free-foil-typecheck
version: 0.0.1
github: "evermake/free-foil-typecheck"
description: Please see the README on GitHub at <https://github.com/evermake/free-foil-typecheck#readme>
synopsis: Type systems implementation powered by Free Foil.
category: Language

extra-source-files:
  - README.md
  - grammar/hindley-milner.cf
  - grammar/system-f.cf

custom-setup:
  dependencies:
    base: ">= 4.11.0.0 && < 5.0"
    process: ">= 1.6.3.0"
    Cabal: ">= 2.4.0.1 && < 4.0"
    PyF:

build-tools:
  BNFC:bnfc: ">= 2.9.4.1"
  alex: ">= 3.2.4"
  happy: ">= 1.19.9"

dependencies:
  base: ">= 4.7 && < 5"
  array: ">= 0.5.3.0"
  bifunctors:
  containers:
  free-foil: ">= 0.2.0"
  unordered-containers: ">= 0.2.20"
  hashable: ">= 1.4.0"

ghc-options:
  - -Wall
  - -Werror

library:
  source-dirs: src
  when:
    - condition: false
      other-modules:
        - FreeFoilTypecheck.HindleyMilner.Parser.Test
        - FreeFoilTypecheck.HindleyMilner.Parser.ErrM
        - FreeFoilTypecheck.HindleyMilner.Parser.Skel

    - condition: false
      other-modules:
        - FreeFoilTypecheck.SystemF.Parser.Test
        - FreeFoilTypecheck.SystemF.Parser.ErrM
        - FreeFoilTypecheck.SystemF.Parser.Skel

executables:
  repl-hm:
    main: Repl.hs
    source-dirs: app/HindleyMilner
    other-modules: []
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - free-foil-typecheck

  interpreter-hm:
    main: Interpreter.hs
    source-dirs: app/HindleyMilner
    other-modules: []
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - free-foil-typecheck

  repl-sf:
    main: Repl.hs
    source-dirs: app/SystemF
    other-modules: []
    dependencies:
      - free-foil-typecheck

  interpreter-sf:
    main: Interpreter.hs
    source-dirs: app/SystemF
    other-modules: []
    dependencies:
      - free-foil-typecheck

tests:
  doctests:
    source-dirs:
      - src/
      - test/doctests
    main: Main.hs
    other-modules: []
    dependencies:
      - free-foil-typecheck
      - doctest-parallel

  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - free-foil-typecheck
      - hspec
      - hspec-discover
      - directory
      - filepath
