-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE DeriveDataTypeable #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language Parser.

module FreeFoilTypecheck.MiniML.Parser.Abs where

import Prelude (Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

import qualified Data.Data    as C (Data, Typeable)
import qualified GHC.Generics as C (Generic)

data Pattern
    = PatternWildcard
    | PatternVar Ident
    | PatternNil
    | PatternPair Pattern Pattern
    | PatternInl Pattern
    | PatternInr Pattern
    | PatternCons Pattern Pattern
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data Exp
    = EVar Ident
    | ETrue
    | EFalse
    | ENat Integer
    | ENil
    | EPair Exp Exp
    | EApp Exp Exp
    | EFst Exp
    | ESnd Exp
    | EInl Exp
    | EInr Exp
    | EIsZero Exp
    | EAdd Exp Exp
    | ESub Exp Exp
    | ECons Exp Exp
    | EIf Exp Exp Exp
    | ELet Pattern Exp ScopedExp
    | ELetRec Pattern ScopedExp ScopedExp
    | EAbs Pattern ScopedExp
    | EFix Pattern ScopedExp
    | ECase Exp [Branch]
    | ETyped Exp Type
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data Branch = Branch Pattern ScopedExp
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data ScopedExp = ScopedExp Exp
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data TypePattern = TPatternVar Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data Type
    = TUVar UVarIdent
    | TNat
    | TBool
    | TVar Ident
    | TList Type
    | TProd Type Type
    | TSum Type Type
    | TArrow Type Type
    | TForAll TypePattern ScopedType
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data ScopedType = ScopedType Type
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic, Data.String.IsString)

newtype UVarIdent = UVarIdent String
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic, Data.String.IsString)

