-- -*- haskell -*- File generated by the BNF Converter (bnfc 2.9.5).

-- Parser definition for use with Happy
{
{-# OPTIONS_GHC -fno-warn-incomplete-patterns -fno-warn-overlapping-patterns #-}
{-# LANGUAGE PatternSynonyms #-}

module FreeFoilTypecheck.MiniML.Parser.Par
  ( happyError
  , myLexer
  , pPattern2
  , pPattern1
  , pPattern
  , pExp6
  , pExp5
  , pExp4
  , pExp3
  , pExp1
  , pExp
  , pExp2
  , pBranch
  , pListBranch
  , pScopedExp
  , pTypePattern
  , pType5
  , pType4
  , pType3
  , pType2
  , pType1
  , pType
  , pScopedType
  ) where

import Prelude

import qualified FreeFoilTypecheck.MiniML.Parser.Abs
import FreeFoilTypecheck.MiniML.Parser.Lex

}

%name pPattern2 Pattern2
%name pPattern1 Pattern1
%name pPattern Pattern
%name pExp6 Exp6
%name pExp5 Exp5
%name pExp4 Exp4
%name pExp3 Exp3
%name pExp1 Exp1
%name pExp Exp
%name pExp2 Exp2
%name pBranch Branch
%name pListBranch ListBranch
%name pScopedExp ScopedExp
%name pTypePattern TypePattern
%name pType5 Type5
%name pType4 Type4
%name pType3 Type3
%name pType2 Type2
%name pType1 Type1
%name pType Type
%name pScopedType ScopedType
-- no lexer declaration
%monad { Err } { (>>=) } { return }
%tokentype {Token}
%token
  '('         { PT _ (TS _ 1)         }
  ')'         { PT _ (TS _ 2)         }
  '*'         { PT _ (TS _ 3)         }
  '+'         { PT _ (TS _ 4)         }
  ','         { PT _ (TS _ 5)         }
  '-'         { PT _ (TS _ 6)         }
  '->'        { PT _ (TS _ 7)         }
  '.'         { PT _ (TS _ 8)         }
  ':'         { PT _ (TS _ 9)         }
  '::'        { PT _ (TS _ 10)        }
  '='         { PT _ (TS _ 11)        }
  'Bool'      { PT _ (TS _ 12)        }
  'List'      { PT _ (TS _ 13)        }
  'Nat'       { PT _ (TS _ 14)        }
  '['         { PT _ (TS _ 15)        }
  ']'         { PT _ (TS _ 16)        }
  '_'         { PT _ (TS _ 17)        }
  'case'      { PT _ (TS _ 18)        }
  'else'      { PT _ (TS _ 19)        }
  'false'     { PT _ (TS _ 20)        }
  'fix'       { PT _ (TS _ 21)        }
  'forall'    { PT _ (TS _ 22)        }
  'fst'       { PT _ (TS _ 23)        }
  'if'        { PT _ (TS _ 24)        }
  'in'        { PT _ (TS _ 25)        }
  'inl'       { PT _ (TS _ 26)        }
  'inr'       { PT _ (TS _ 27)        }
  'iszero'    { PT _ (TS _ 28)        }
  'let'       { PT _ (TS _ 29)        }
  'letrec'    { PT _ (TS _ 30)        }
  'of'        { PT _ (TS _ 31)        }
  'snd'       { PT _ (TS _ 32)        }
  'then'      { PT _ (TS _ 33)        }
  'true'      { PT _ (TS _ 34)        }
  '{'         { PT _ (TS _ 35)        }
  '|'         { PT _ (TS _ 36)        }
  '}'         { PT _ (TS _ 37)        }
  'λ'         { PT _ (TS _ 38)        }
  L_Ident     { PT _ (TV $$)          }
  L_integ     { PT _ (TI $$)          }
  L_UVarIdent { PT _ (T_UVarIdent $$) }

%%

Ident :: { FreeFoilTypecheck.MiniML.Parser.Abs.Ident }
Ident  : L_Ident { FreeFoilTypecheck.MiniML.Parser.Abs.Ident $1 }

Integer :: { Integer }
Integer  : L_integ  { (read $1) :: Integer }

UVarIdent :: { FreeFoilTypecheck.MiniML.Parser.Abs.UVarIdent }
UVarIdent  : L_UVarIdent { FreeFoilTypecheck.MiniML.Parser.Abs.UVarIdent $1 }

Pattern2 :: { FreeFoilTypecheck.MiniML.Parser.Abs.Pattern }
Pattern2
  : '_' { FreeFoilTypecheck.MiniML.Parser.Abs.PatternWildcard }
  | Ident { FreeFoilTypecheck.MiniML.Parser.Abs.PatternVar $1 }
  | '[' ']' { FreeFoilTypecheck.MiniML.Parser.Abs.PatternNil }
  | '(' Pattern ',' Pattern ')' { FreeFoilTypecheck.MiniML.Parser.Abs.PatternPair $2 $4 }
  | '(' Pattern ')' { $2 }

Pattern1 :: { FreeFoilTypecheck.MiniML.Parser.Abs.Pattern }
Pattern1
  : 'inl' Pattern2 { FreeFoilTypecheck.MiniML.Parser.Abs.PatternInl $2 }
  | 'inr' Pattern2 { FreeFoilTypecheck.MiniML.Parser.Abs.PatternInr $2 }
  | Pattern2 { $1 }

Pattern :: { FreeFoilTypecheck.MiniML.Parser.Abs.Pattern }
Pattern
  : Pattern1 '::' Pattern { FreeFoilTypecheck.MiniML.Parser.Abs.PatternCons $1 $3 }
  | Pattern1 { $1 }

Exp6 :: { FreeFoilTypecheck.MiniML.Parser.Abs.Exp }
Exp6
  : Ident { FreeFoilTypecheck.MiniML.Parser.Abs.EVar $1 }
  | 'true' { FreeFoilTypecheck.MiniML.Parser.Abs.ETrue }
  | 'false' { FreeFoilTypecheck.MiniML.Parser.Abs.EFalse }
  | Integer { FreeFoilTypecheck.MiniML.Parser.Abs.ENat $1 }
  | '[' ']' { FreeFoilTypecheck.MiniML.Parser.Abs.ENil }
  | '(' Exp1 ',' Exp1 ')' { FreeFoilTypecheck.MiniML.Parser.Abs.EPair $2 $4 }
  | '(' Exp ')' { $2 }

Exp5 :: { FreeFoilTypecheck.MiniML.Parser.Abs.Exp }
Exp5
  : Exp5 Exp6 { FreeFoilTypecheck.MiniML.Parser.Abs.EApp $1 $2 }
  | 'fst' Exp6 { FreeFoilTypecheck.MiniML.Parser.Abs.EFst $2 }
  | 'snd' Exp6 { FreeFoilTypecheck.MiniML.Parser.Abs.ESnd $2 }
  | 'inl' Exp6 { FreeFoilTypecheck.MiniML.Parser.Abs.EInl $2 }
  | 'inr' Exp6 { FreeFoilTypecheck.MiniML.Parser.Abs.EInr $2 }
  | 'iszero' Exp6 { FreeFoilTypecheck.MiniML.Parser.Abs.EIsZero $2 }
  | Exp6 { $1 }

Exp4 :: { FreeFoilTypecheck.MiniML.Parser.Abs.Exp }
Exp4
  : Exp4 '+' Exp5 { FreeFoilTypecheck.MiniML.Parser.Abs.EAdd $1 $3 }
  | Exp4 '-' Exp5 { FreeFoilTypecheck.MiniML.Parser.Abs.ESub $1 $3 }
  | Exp5 { $1 }

Exp3 :: { FreeFoilTypecheck.MiniML.Parser.Abs.Exp }
Exp3
  : Exp4 '::' Exp3 { FreeFoilTypecheck.MiniML.Parser.Abs.ECons $1 $3 }
  | Exp4 { $1 }

Exp1 :: { FreeFoilTypecheck.MiniML.Parser.Abs.Exp }
Exp1
  : 'if' Exp1 'then' Exp1 'else' Exp1 { FreeFoilTypecheck.MiniML.Parser.Abs.EIf $2 $4 $6 }
  | 'let' Pattern '=' Exp1 'in' ScopedExp { FreeFoilTypecheck.MiniML.Parser.Abs.ELet $2 $4 $6 }
  | 'letrec' Pattern '=' ScopedExp 'in' ScopedExp { FreeFoilTypecheck.MiniML.Parser.Abs.ELetRec $2 $4 $6 }
  | 'λ' Pattern '.' ScopedExp { FreeFoilTypecheck.MiniML.Parser.Abs.EAbs $2 $4 }
  | 'fix' Pattern '.' ScopedExp { FreeFoilTypecheck.MiniML.Parser.Abs.EFix $2 $4 }
  | 'case' Exp1 'of' '{' ListBranch '}' { FreeFoilTypecheck.MiniML.Parser.Abs.ECase $2 $5 }
  | Exp2 { $1 }

Exp :: { FreeFoilTypecheck.MiniML.Parser.Abs.Exp }
Exp
  : Exp1 ':' Type { FreeFoilTypecheck.MiniML.Parser.Abs.ETyped $1 $3 }
  | Exp1 { $1 }

Exp2 :: { FreeFoilTypecheck.MiniML.Parser.Abs.Exp }
Exp2 : Exp3 { $1 }

Branch :: { FreeFoilTypecheck.MiniML.Parser.Abs.Branch }
Branch
  : Pattern '->' ScopedExp { FreeFoilTypecheck.MiniML.Parser.Abs.Branch $1 $3 }

ListBranch :: { [FreeFoilTypecheck.MiniML.Parser.Abs.Branch] }
ListBranch
  : Branch { (:[]) $1 } | Branch '|' ListBranch { (:) $1 $3 }

ScopedExp :: { FreeFoilTypecheck.MiniML.Parser.Abs.ScopedExp }
ScopedExp
  : Exp1 { FreeFoilTypecheck.MiniML.Parser.Abs.ScopedExp $1 }

TypePattern :: { FreeFoilTypecheck.MiniML.Parser.Abs.TypePattern }
TypePattern
  : Ident { FreeFoilTypecheck.MiniML.Parser.Abs.TPatternVar $1 }

Type5 :: { FreeFoilTypecheck.MiniML.Parser.Abs.Type }
Type5
  : UVarIdent { FreeFoilTypecheck.MiniML.Parser.Abs.TUVar $1 }
  | 'Nat' { FreeFoilTypecheck.MiniML.Parser.Abs.TNat }
  | 'Bool' { FreeFoilTypecheck.MiniML.Parser.Abs.TBool }
  | Ident { FreeFoilTypecheck.MiniML.Parser.Abs.TVar $1 }
  | '(' Type ')' { $2 }

Type4 :: { FreeFoilTypecheck.MiniML.Parser.Abs.Type }
Type4
  : 'List' Type5 { FreeFoilTypecheck.MiniML.Parser.Abs.TList $2 }
  | Type5 { $1 }

Type3 :: { FreeFoilTypecheck.MiniML.Parser.Abs.Type }
Type3
  : Type4 '*' Type3 { FreeFoilTypecheck.MiniML.Parser.Abs.TProd $1 $3 }
  | Type4 { $1 }

Type2 :: { FreeFoilTypecheck.MiniML.Parser.Abs.Type }
Type2
  : Type3 '+' Type2 { FreeFoilTypecheck.MiniML.Parser.Abs.TSum $1 $3 }
  | Type3 { $1 }

Type1 :: { FreeFoilTypecheck.MiniML.Parser.Abs.Type }
Type1
  : Type2 '->' Type1 { FreeFoilTypecheck.MiniML.Parser.Abs.TArrow $1 $3 }
  | Type2 { $1 }

Type :: { FreeFoilTypecheck.MiniML.Parser.Abs.Type }
Type
  : 'forall' TypePattern '.' ScopedType { FreeFoilTypecheck.MiniML.Parser.Abs.TForAll $2 $4 }
  | Type1 { $1 }

ScopedType :: { FreeFoilTypecheck.MiniML.Parser.Abs.ScopedType }
ScopedType
  : Type1 { FreeFoilTypecheck.MiniML.Parser.Abs.ScopedType $1 }

{

type Err = Either String

happyError :: [Token] -> Err a
happyError ts = Left $
  "syntax error at " ++ tokenPos ts ++
  case ts of
    []      -> []
    [Err _] -> " due to lexer error"
    t:_     -> " before `" ++ (prToken t) ++ "'"

myLexer :: String -> [Token]
myLexer = tokens

}

