-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for FreeFoilTypecheck.

module FreeFoilTypecheck.MiniML.Parser.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified FreeFoilTypecheck.MiniML.Parser.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print FreeFoilTypecheck.MiniML.Parser.Abs.Ident where
  prt _ (FreeFoilTypecheck.MiniML.Parser.Abs.Ident i) = doc $ showString i
instance Print FreeFoilTypecheck.MiniML.Parser.Abs.UVarIdent where
  prt _ (FreeFoilTypecheck.MiniML.Parser.Abs.UVarIdent i) = doc $ showString i
instance Print FreeFoilTypecheck.MiniML.Parser.Abs.Pattern where
  prt i = \case
    FreeFoilTypecheck.MiniML.Parser.Abs.PatternWildcard -> prPrec i 2 (concatD [doc (showString "_")])
    FreeFoilTypecheck.MiniML.Parser.Abs.PatternVar id_ -> prPrec i 2 (concatD [prt 0 id_])
    FreeFoilTypecheck.MiniML.Parser.Abs.PatternNil -> prPrec i 2 (concatD [doc (showString "["), doc (showString "]")])
    FreeFoilTypecheck.MiniML.Parser.Abs.PatternPair pattern_1 pattern_2 -> prPrec i 2 (concatD [doc (showString "("), prt 0 pattern_1, doc (showString ","), prt 0 pattern_2, doc (showString ")")])
    FreeFoilTypecheck.MiniML.Parser.Abs.PatternInl pattern_ -> prPrec i 1 (concatD [doc (showString "inl"), prt 2 pattern_])
    FreeFoilTypecheck.MiniML.Parser.Abs.PatternInr pattern_ -> prPrec i 1 (concatD [doc (showString "inr"), prt 2 pattern_])
    FreeFoilTypecheck.MiniML.Parser.Abs.PatternCons pattern_1 pattern_2 -> prPrec i 0 (concatD [prt 1 pattern_1, doc (showString "::"), prt 0 pattern_2])

instance Print FreeFoilTypecheck.MiniML.Parser.Abs.Exp where
  prt i = \case
    FreeFoilTypecheck.MiniML.Parser.Abs.EVar id_ -> prPrec i 6 (concatD [prt 0 id_])
    FreeFoilTypecheck.MiniML.Parser.Abs.ETrue -> prPrec i 6 (concatD [doc (showString "true")])
    FreeFoilTypecheck.MiniML.Parser.Abs.EFalse -> prPrec i 6 (concatD [doc (showString "false")])
    FreeFoilTypecheck.MiniML.Parser.Abs.ENat n -> prPrec i 6 (concatD [prt 0 n])
    FreeFoilTypecheck.MiniML.Parser.Abs.ENil -> prPrec i 6 (concatD [doc (showString "["), doc (showString "]")])
    FreeFoilTypecheck.MiniML.Parser.Abs.EPair exp1 exp2 -> prPrec i 6 (concatD [doc (showString "("), prt 1 exp1, doc (showString ","), prt 1 exp2, doc (showString ")")])
    FreeFoilTypecheck.MiniML.Parser.Abs.EApp exp1 exp2 -> prPrec i 5 (concatD [prt 5 exp1, prt 6 exp2])
    FreeFoilTypecheck.MiniML.Parser.Abs.EFst exp -> prPrec i 5 (concatD [doc (showString "fst"), prt 6 exp])
    FreeFoilTypecheck.MiniML.Parser.Abs.ESnd exp -> prPrec i 5 (concatD [doc (showString "snd"), prt 6 exp])
    FreeFoilTypecheck.MiniML.Parser.Abs.EInl exp -> prPrec i 5 (concatD [doc (showString "inl"), prt 6 exp])
    FreeFoilTypecheck.MiniML.Parser.Abs.EInr exp -> prPrec i 5 (concatD [doc (showString "inr"), prt 6 exp])
    FreeFoilTypecheck.MiniML.Parser.Abs.EIsZero exp -> prPrec i 5 (concatD [doc (showString "iszero"), prt 6 exp])
    FreeFoilTypecheck.MiniML.Parser.Abs.EAdd exp1 exp2 -> prPrec i 4 (concatD [prt 4 exp1, doc (showString "+"), prt 5 exp2])
    FreeFoilTypecheck.MiniML.Parser.Abs.ESub exp1 exp2 -> prPrec i 4 (concatD [prt 4 exp1, doc (showString "-"), prt 5 exp2])
    FreeFoilTypecheck.MiniML.Parser.Abs.ECons exp1 exp2 -> prPrec i 3 (concatD [prt 4 exp1, doc (showString "::"), prt 3 exp2])
    FreeFoilTypecheck.MiniML.Parser.Abs.EIf exp1 exp2 exp3 -> prPrec i 1 (concatD [doc (showString "if"), prt 1 exp1, doc (showString "then"), prt 1 exp2, doc (showString "else"), prt 1 exp3])
    FreeFoilTypecheck.MiniML.Parser.Abs.ELet pattern_ exp scopedexp -> prPrec i 1 (concatD [doc (showString "let"), prt 0 pattern_, doc (showString "="), prt 1 exp, doc (showString "in"), prt 0 scopedexp])
    FreeFoilTypecheck.MiniML.Parser.Abs.ELetRec pattern_ scopedexp1 scopedexp2 -> prPrec i 1 (concatD [doc (showString "letrec"), prt 0 pattern_, doc (showString "="), prt 0 scopedexp1, doc (showString "in"), prt 0 scopedexp2])
    FreeFoilTypecheck.MiniML.Parser.Abs.EAbs pattern_ scopedexp -> prPrec i 1 (concatD [doc (showString "\955"), prt 0 pattern_, doc (showString "."), prt 0 scopedexp])
    FreeFoilTypecheck.MiniML.Parser.Abs.EFix pattern_ scopedexp -> prPrec i 1 (concatD [doc (showString "fix"), prt 0 pattern_, doc (showString "."), prt 0 scopedexp])
    FreeFoilTypecheck.MiniML.Parser.Abs.ECase exp branchs -> prPrec i 1 (concatD [doc (showString "case"), prt 1 exp, doc (showString "of"), doc (showString "{"), prt 0 branchs, doc (showString "}")])
    FreeFoilTypecheck.MiniML.Parser.Abs.ETyped exp type_ -> prPrec i 0 (concatD [prt 1 exp, doc (showString ":"), prt 0 type_])

instance Print FreeFoilTypecheck.MiniML.Parser.Abs.Branch where
  prt i = \case
    FreeFoilTypecheck.MiniML.Parser.Abs.Branch pattern_ scopedexp -> prPrec i 0 (concatD [prt 0 pattern_, doc (showString "->"), prt 0 scopedexp])

instance Print [FreeFoilTypecheck.MiniML.Parser.Abs.Branch] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString "|"), prt 0 xs]

instance Print FreeFoilTypecheck.MiniML.Parser.Abs.ScopedExp where
  prt i = \case
    FreeFoilTypecheck.MiniML.Parser.Abs.ScopedExp exp -> prPrec i 0 (concatD [prt 1 exp])

instance Print FreeFoilTypecheck.MiniML.Parser.Abs.TypePattern where
  prt i = \case
    FreeFoilTypecheck.MiniML.Parser.Abs.TPatternVar id_ -> prPrec i 0 (concatD [prt 0 id_])

instance Print FreeFoilTypecheck.MiniML.Parser.Abs.Type where
  prt i = \case
    FreeFoilTypecheck.MiniML.Parser.Abs.TUVar uvarident -> prPrec i 5 (concatD [prt 0 uvarident])
    FreeFoilTypecheck.MiniML.Parser.Abs.TNat -> prPrec i 5 (concatD [doc (showString "Nat")])
    FreeFoilTypecheck.MiniML.Parser.Abs.TBool -> prPrec i 5 (concatD [doc (showString "Bool")])
    FreeFoilTypecheck.MiniML.Parser.Abs.TVar id_ -> prPrec i 5 (concatD [prt 0 id_])
    FreeFoilTypecheck.MiniML.Parser.Abs.TList type_ -> prPrec i 4 (concatD [doc (showString "List"), prt 5 type_])
    FreeFoilTypecheck.MiniML.Parser.Abs.TProd type_1 type_2 -> prPrec i 3 (concatD [prt 4 type_1, doc (showString "*"), prt 3 type_2])
    FreeFoilTypecheck.MiniML.Parser.Abs.TSum type_1 type_2 -> prPrec i 2 (concatD [prt 3 type_1, doc (showString "+"), prt 2 type_2])
    FreeFoilTypecheck.MiniML.Parser.Abs.TArrow type_1 type_2 -> prPrec i 1 (concatD [prt 2 type_1, doc (showString "->"), prt 1 type_2])
    FreeFoilTypecheck.MiniML.Parser.Abs.TForAll typepattern scopedtype -> prPrec i 0 (concatD [doc (showString "forall"), prt 0 typepattern, doc (showString "."), prt 0 scopedtype])

instance Print FreeFoilTypecheck.MiniML.Parser.Abs.ScopedType where
  prt i = \case
    FreeFoilTypecheck.MiniML.Parser.Abs.ScopedType type_ -> prPrec i 0 (concatD [prt 1 type_])
