-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module FreeFoilTypecheck.MiniML.Parser.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified FreeFoilTypecheck.MiniML.Parser.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: FreeFoilTypecheck.MiniML.Parser.Abs.Ident -> Result
transIdent x = case x of
  FreeFoilTypecheck.MiniML.Parser.Abs.Ident string -> failure x

transUVarIdent :: FreeFoilTypecheck.MiniML.Parser.Abs.UVarIdent -> Result
transUVarIdent x = case x of
  FreeFoilTypecheck.MiniML.Parser.Abs.UVarIdent string -> failure x

transPattern :: FreeFoilTypecheck.MiniML.Parser.Abs.Pattern -> Result
transPattern x = case x of
  FreeFoilTypecheck.MiniML.Parser.Abs.PatternWildcard -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.PatternVar ident -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.PatternNil -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.PatternPair pattern_1 pattern_2 -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.PatternInl pattern_ -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.PatternInr pattern_ -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.PatternCons pattern_1 pattern_2 -> failure x

transExp :: FreeFoilTypecheck.MiniML.Parser.Abs.Exp -> Result
transExp x = case x of
  FreeFoilTypecheck.MiniML.Parser.Abs.EVar ident -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.ETrue -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.EFalse -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.ENat integer -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.ENil -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.EPair exp1 exp2 -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.EApp exp1 exp2 -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.EFst exp -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.ESnd exp -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.EInl exp -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.EInr exp -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.EIsZero exp -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.EAdd exp1 exp2 -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.ESub exp1 exp2 -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.ECons exp1 exp2 -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.EIf exp1 exp2 exp3 -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.ELet pattern_ exp scopedexp -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.ELetRec pattern_ scopedexp1 scopedexp2 -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.EAbs pattern_ scopedexp -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.EFix pattern_ scopedexp -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.ECase exp branchs -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.ETyped exp type_ -> failure x

transBranch :: FreeFoilTypecheck.MiniML.Parser.Abs.Branch -> Result
transBranch x = case x of
  FreeFoilTypecheck.MiniML.Parser.Abs.Branch pattern_ scopedexp -> failure x

transScopedExp :: FreeFoilTypecheck.MiniML.Parser.Abs.ScopedExp -> Result
transScopedExp x = case x of
  FreeFoilTypecheck.MiniML.Parser.Abs.ScopedExp exp -> failure x

transTypePattern :: FreeFoilTypecheck.MiniML.Parser.Abs.TypePattern -> Result
transTypePattern x = case x of
  FreeFoilTypecheck.MiniML.Parser.Abs.TPatternVar ident -> failure x

transType :: FreeFoilTypecheck.MiniML.Parser.Abs.Type -> Result
transType x = case x of
  FreeFoilTypecheck.MiniML.Parser.Abs.TUVar uvarident -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.TNat -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.TBool -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.TVar ident -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.TList type_ -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.TProd type_1 type_2 -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.TSum type_1 type_2 -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.TArrow type_1 type_2 -> failure x
  FreeFoilTypecheck.MiniML.Parser.Abs.TForAll typepattern scopedtype -> failure x

transScopedType :: FreeFoilTypecheck.MiniML.Parser.Abs.ScopedType -> Result
transScopedType x = case x of
  FreeFoilTypecheck.MiniML.Parser.Abs.ScopedType type_ -> failure x
