-- | Scope checking of raw (BNFC) terms before conversion to the scope-safe
-- representation.
--
-- The conversion generated by free-foil 0.2.0 calls 'error' on an unbound
-- variable. To report such programs as ordinary errors, we check that a raw
-- term is closed before converting it.
module FreeFoilTypecheck.ScopeCheck
  ( checkClosed,
    checkClosedWith,
  )
where

import Data.Bifoldable (Bifoldable, bitraverse_)
import qualified Data.Set as Set

-- | Check that a raw term has no free variables.
-- On failure, returns the first unbound variable.
checkClosed ::
  (Ord name, Bifoldable sig) =>
  -- | Peel one node of a raw term (generated with @mkConvertToFreeFoil@).
  (term -> Either name (sig (pattern, scoped) term)) ->
  -- | Variables bound by a raw pattern.
  (pattern -> [name]) ->
  -- | Body of a raw scoped term (generated with @mkConvertToFreeFoil@).
  (scoped -> term) ->
  term ->
  Either name ()
checkClosed = checkClosedWith []

-- | Like 'checkClosed', but with some variables already in scope.
checkClosedWith ::
  (Ord name, Bifoldable sig) =>
  [name] ->
  (term -> Either name (sig (pattern, scoped) term)) ->
  (pattern -> [name]) ->
  (scoped -> term) ->
  term ->
  Either name ()
checkClosedWith initial peel binders unscope = go (Set.fromList initial)
  where
    go bound term = case peel term of
      Left x
        | x `Set.member` bound -> Right ()
        | otherwise -> Left x
      Right node -> bitraverse_ goScoped (go bound) node
      where
        goScoped (pat, scoped) =
          go (foldr Set.insert bound (binders pat)) (unscope scoped)
